### PR TITLE
PR with a base working RESTful WS 

### PR DESCRIPTION
**Pull request by AlexFlFe**
PR with an initial working WS and with a correct folder structure to work as a base for the project.
#2

### CODE REVIEW

**Review by AleXKiD31 — APPROVED** [review]
LGTM

**Review by SaraVictorFernandez — APPROVED** [review]
great greeting :)

**Review by JordiJT99 — APPROVED** [review]

**Review by kianMIC — APPROVED** [review]
All fine

**Review by Albamph — APPROVED** [review]
Mucho más pragmático utilizar el record en este caso! Gracias!

**Pull request merged**
